// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp2HZ6mXSy94QnzqzeeZXZvJEyzXwbXTE',
    appId: '1:27602600942:web:3026fd3cde6bff320cc4ff',
    messagingSenderId: '27602600942',
    projectId: 'crud-firebase-eb883',
    authDomain: 'crud-firebase-eb883.firebaseapp.com',
    storageBucket: 'crud-firebase-eb883.appspot.com',
    measurementId: 'G-JB5DH22GRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4u208SixmRUE-FIQghCc-StAKCplDyPU',
    appId: '1:27602600942:android:8a1dfcedfac8d2760cc4ff',
    messagingSenderId: '27602600942',
    projectId: 'crud-firebase-eb883',
    storageBucket: 'crud-firebase-eb883.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd7D3hiyOuwn9TeLqFhoV9R7LWsEWO-kg',
    appId: '1:27602600942:ios:e303d39436b70d240cc4ff',
    messagingSenderId: '27602600942',
    projectId: 'crud-firebase-eb883',
    storageBucket: 'crud-firebase-eb883.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd7D3hiyOuwn9TeLqFhoV9R7LWsEWO-kg',
    appId: '1:27602600942:ios:e303d39436b70d240cc4ff',
    messagingSenderId: '27602600942',
    projectId: 'crud-firebase-eb883',
    storageBucket: 'crud-firebase-eb883.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp2HZ6mXSy94QnzqzeeZXZvJEyzXwbXTE',
    appId: '1:27602600942:web:e17ba93c764bf54c0cc4ff',
    messagingSenderId: '27602600942',
    projectId: 'crud-firebase-eb883',
    authDomain: 'crud-firebase-eb883.firebaseapp.com',
    storageBucket: 'crud-firebase-eb883.appspot.com',
    measurementId: 'G-C3F7K102YL',
  );
}
